### ISSUE TITLE
Scheduled 2017 iSWP data refresh for SWP amendment

### ISSUE THREAD

**Issue by lebell** [TNRIS/iswp2017#248] opened 2017-12-04 15:48 UTC
This Thursday, 12/7 a SWP amendment will go to the Board for approval. IT will update the database that afternoon after the changes have been officially approved.

Could you please refresh the 2017 iSWP data this Friday, 12/8 to display the amendment changes without pushing any development changes to production?

**Comment by DavidHickman** [comment] 2017-12-04 16:19
That shouldn't be a problem. Should we wait for your signal that everything is ready to refresh, or just go ahead and refresh Friday morning?

**Comment by lebell** [comment] 2017-12-04 16:23
Great, we will double check that the updates went through that morning and then message you when it's clear to refresh. Thank you!

**Comment by DavidHickman** [comment] 2017-12-04 16:38
Sounds great! Thank you!

**Comment by lebell** [comment] 2017-12-07 19:47
The updates have been made and reviewed on prod. Please refresh whenever you have an opportunity. Thank you!

**Comment by DavidHickman** [comment] 2017-12-08 20:24
@lebell We're working on the update now, but it's taking a little longer than expected. I'll update the issue as soon as the redeployment is complete so you can verify the new data. Thanks!

**Comment by DavidHickman** [comment] 2017-12-08 21:09
Is there a data update test case we can check for to verify the update was successful? It has not been deployed yet, we want to check locally first.

**Comment by SabrinaAnderson** [comment] 2017-12-08 21:29
Select data type 'Water User Group' with a value of 'San Marcos' and make sure that the WMS named 'GBRA - MBWSP - CONJUNCTIVE USE (OPTION 3A) - ASR' is listed with it under recommended strategy supply. It should show a strategy supply value of 4,581 acre-feet in 2060 and 5,717 acre-feet in 2070.

Another check would be to select the data type WMS Project and then enter the value 'McLennan County Regional Arsenic Mitigation - Riesel' to make sure that the data for that project displays. 

Please let us know if you need anything else.

**Comment by DavidHickman** [comment] 2017-12-08 21:59
Hey @SabrinaAnderson 

We've identified an issue that complicates this data refresh and want to give you some options on how to proceed. The updated data is in the new database schema, but the previous app code is still written for the legacy database schema (ex: WMSProjectId vs. WmsProjectId).

**We have a couple of options:**

1. We are making good progress with the new version of the application following the feedback you provided. We could continue that development and deploy it all at once. We've already tested the new data against the staging version and everything works great.
2. We could temporarily pause work on the new application version to update the legacy application to digest the new database schema. This would likely take a few days.

We either delay deployment of the updated app version or delay deployment of the updated data. I'm not sure which option is more preferable based on your priorities, but we can certainly do either.

Thanks!

**Comment by SabrinaAnderson** [comment] 2017-12-08 22:13
I really don't want to create extra work for y'all, but we need to update the iSWP application with the updated data so that the new projects display.

 Laura suggested we revert our database back to the old schema so that you can push the SWP amendment changes. Then we would update it again to the new schema after you've made the SWP amendment changes. Would that work? If so, we could work with IT to get that done early next week.

**Comment by DavidHickman** [comment] 2017-12-08 22:51
It's no problem! We weren't sure what the priority was from your perspective. I'm happy to make the updates to the application code. I'm not sure what level of effort or time is involved in making the database schema updates, so I'll defer to you on whether we update the application or revert the database. I think we could make the necessary application updates and redeploy by midweek if we start on Monday.

Have a great weekend!

**Comment by DavidHickman** [comment] 2017-12-11 14:13
Hi @SabrinaAnderson and @lebell 

Jason and I started updating the legacy (current production) version of the app this morning and I think we'll be able to push the updated data to production relatively quickly without your team or IT needing to make any changes to the database schema. I'll let you know as soon as we've pushed the new data to the production site.

**Comment by SabrinaAnderson** [comment] 2017-12-11 14:34
Thank you so much for doing that! We were just discussing which route would have the least amount of impact on everyone. Please let us know if we can do anything to help.

**Comment by DavidHickman** [comment] 2017-12-11 15:36
We've redeployed the site and checked the test cases that @SabrinaAnderson supplied. Everything looks good. I think the process went much faster than anticipated since we had the spreadsheet @lebell provided for the new app version and we had gone through the process once before.

Please verify the site/data at your convenience and let us know if we can close this issue.

Thanks!

**Comment by SabrinaAnderson** [comment] 2017-12-11 16:20
You did great, but while reviewing the new projects I realized that I forgot to update the coordinates for one of the new projects. They have been added now and I confirmed that all projects in the view [map].[vw2017MapWMSProjects] have lat/longs. I'm sorry about that. Would you please refresh the data another time?

I found another issue, but I think that it may be tied to the missing coordinates. After you push the changes, I'll check again and see if it was resolved.

Thank you for the quick turnaround on this!

**Comment by DavidHickman** [comment] 2017-12-11 16:33
No problem! We'll let you know when the app has been redeployed.

**Comment by DavidHickman** [comment] 2017-12-11 18:26
@SabrinaAnderson The app has been redeployed.Let us know if the issue you noticed persists. Thanks!

**Comment by SabrinaAnderson** [comment] 2017-12-11 18:52
Unfortunately, the problem persists, but it is a strange bug. IE and Chrome are behaving differently. What I initially found in Chrome is when a WUG was related to the project that had missing coordinates, I couldn't change the filters on the raw data table or change the decade values displayed. This same functionality was working fine for other WUGs not related to the project in Chrome. After the refresh, the issue persisted in Chrome, but I checked IE and it is working fine. WUG examples to look at in Chrome are Wimberley and Lockhart, both are using the project that had the missing coordinates. You can search for the project by using the text 'Option 3A.'

In IE, I am having trouble with the "view data for" dropdown list in the top menu bar. When I try to scroll down the list using the sidebar and choose Water User Group, it doesn't let me. I have to use the scroll wheel on my mouse. I checked Chrome and this is not an issue there.

**Comment by SabrinaAnderson** [comment] 2017-12-11 18:57
Depending on how you choose to proceed with the updates, I found one other missing data item that I forgot to update. The MapSourceName is generated manually (via database change request) for each new source added to the database. I had to add a new source when making the amendment changes and forgot to create it. We can submit the data change request to get it updated now, but I doubt anyone will notice this missing source name except for me since the source name isn't hyperlinked at this time. So unless we can get it in the database while you are fixing the bugs posted above, this data refresh can wait until the next deployment of the new pages.

**Comment by SabrinaAnderson** [comment] 2017-12-11 19:15
I've decided to wait to make the updates for that new source because it will also require an update to the shapefile used by the application in addition to a data refresh. We will work with y'all to make the changes before the next deployment to production with the new application pages. Sorry about all the missing data. SWP amendments come up once in a blue moon and this is the first time they are being made to the new DB17 database.

**Comment by DavidHickman** [comment] 2017-12-11 19:37
This data refresh is complete. Will revisit in https://github.com/TNRIS/iswp2017/issues/261

**Closed by DavidHickman** 2017-12-11 19:37 UTC
Labels: Data Refresh
